import type {CanasterTheme, CanasterThemeId, CanasterThemeTexture} from './CanasterTheme';

export const DEFAULT_CANASTER_THEME_ID: CanasterThemeId = 'paperWorkbench';

const fontFamily =
    'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';

const typography = {
    family: fontFamily,
    titleSize: '15px',
    bodySize: '13px',
    labelSize: '12px',
    microSize: '11px',
    titleWeight: 600,
    strongWeight: 700,
    bodyWeight: 400,
    titleLineHeight: '1.2',
    bodyLineHeight: '1.38',
    labelLineHeight: '1.2',
};

const spacing = {
    xxs: '4px',
    xs: '6px',
    sm: '8px',
    md: '12px',
    lg: '14px',
    xl: '18px',
};

const radius = {
    xs: '3px',
    sm: '4px',
    md: '6px',
    lg: '8px',
    panel: '8px',
    node: '8px',
    control: '6px',
};

const borders = {
    width: '1px',
    focusWidth: '2px',
    selectedWidth: '3px',
};

const motion = {
    fast: '120ms',
    base: '180ms',
    slow: '240ms',
    easeOut: 'cubic-bezier(0.16, 1, 0.3, 1)',
};

const components = {
    toolbar: {
        height: '40px',
        padding: '6px 8px',
        gap: '8px',
    },
    iconButton: {
        size: '32px',
        mobileSize: '28px',
        iconSize: 17,
    },
    panel: {
        padding: '8px',
        gap: '8px',
    },
    node: {
        padding: '12px',
        titleSize: '15px',
        bodySize: '13px',
        badgeSize: '10px',
    },
    drawer: {
        width: '320px',
    },
    input: {
        height: '30px',
        paddingInline: '8px',
    },
    menu: {
        width: '224px',
    },
};

const flatTexture: CanasterThemeTexture = {
    canvasBackgroundImage: 'none',
    canvasBackgroundBlendMode: 'normal',
    canvasWash: 'transparent',
    canvasWashOpacity: 0,
    canvasPattern: {
        kind: 'line-grid',
        opacity: 1,
        embeddedOpacity: 0.5,
        dotRadius: 1,
        hatchAngle: -28,
        hatchLength: 8,
    },
    panelBackdropFilter: 'none',
    panelSurfaceTreatment: 'solid',
    paneGutter: '16px',
    nodeSurfaceTreatment: 'solid',
    gridStep: 32,
    gridMajorEvery: 4,
    gridLineWidth: 1,
    gridDash: [],
    nodeRadius: 8,
    nodeRestBorderWidth: 1.2,
    nodeHoverBorderWidth: 1.8,
    nodeSelectedBorderWidth: 2.2,
    nodePrimaryBorderWidth: 3,
    nodeShadowBlur: 10,
    nodeSelectedShadowBlur: 14,
    nodeShadowOffsetY: 5,
};

export const CANASTER_THEMES: Record<CanasterThemeId, CanasterTheme> = {
    paperWorkbench: {
        id: 'paperWorkbench',
        name: 'Default Workbench',
        mode: 'light',
        description: 'Crisp light workspace for daily operational planning.',
        colors: {
            canvas: {
                background: '#f3f6f7',
                grid: 'rgba(45, 64, 76, 0.14)',
                gridMajor: 'rgba(28, 47, 59, 0.27)',
                paneFill: 'rgba(252, 254, 255, 0.97)',
                paneBorder: 'rgba(58, 79, 93, 0.36)',
                paneBorderInner: 'rgba(255, 255, 255, 0.92)',
                paneResizer: 'rgba(50, 72, 87, 0.24)',
                paneResizerMuted: 'rgba(50, 72, 87, 0.14)',
                paneResizerStrong: 'rgba(18, 37, 49, 0.62)',
                parentShape: 'rgba(52, 77, 91, 0.18)',
                parentShapeBorder: 'rgba(24, 44, 57, 0.35)',
                portalShape: 'rgba(16, 104, 137, 0.13)',
                portalShapeBorder: 'rgba(16, 104, 137, 0.58)',
            },
            panel: {
                surface: 'rgba(253, 254, 255, 0.98)',
                surfaceMuted: 'rgba(32, 52, 66, 0.055)',
                surfaceRaised: '#ffffff',
                border: '#c0cbd2',
                borderStrong: 'rgba(24, 44, 57, 0.34)',
            },
            node: {
                surface: '#fcfefe',
                border: '#b8c5ce',
                selected: '#0d7192',
                resizeFill: '#ad7522',
                shadow: 'rgba(35, 56, 70, 0.13)',
                task: '#0d7192',
                data: '#26785f',
                system: '#9a6a1d',
            },
            text: {
                high: '#152633',
                body: '#344957',
                muted: '#5f7481',
                inverse: '#ffffff',
                placeholder: '#536a78',
            },
            action: {
                primary: '#0d7192',
                primaryHover: '#075a77',
                primarySoft: 'rgba(13, 113, 146, 0.12)',
                focus: '#0d7192',
            },
            state: {
                success: '#26785f',
                successSoft: 'rgba(38, 120, 95, 0.13)',
                warning: '#9a6a1d',
                warningSoft: 'rgba(154, 106, 29, 0.14)',
                error: '#ad2d3c',
                errorSoft: 'rgba(173, 45, 60, 0.12)',
            },
            overlay: {
                scrim: 'rgba(21, 38, 51, 0.34)',
                hover: 'rgba(21, 38, 51, 0.07)',
                active: 'rgba(21, 38, 51, 0.11)',
            },
        },
        typography,
        spacing,
        radius,
        borders,
        shadows: {
            chrome: '0 10px 24px rgba(35, 56, 70, 0.12)',
            node: '0 4px 10px rgba(35, 56, 70, 0.1)',
            nodeSelected: '0 7px 16px rgba(35, 56, 70, 0.16)',
            modal: '0 18px 44px rgba(35, 56, 70, 0.22)',
            menu: '0 12px 26px rgba(35, 56, 70, 0.16)',
        },
        texture: {
            ...flatTexture,
            canvasPattern: {
                ...flatTexture.canvasPattern,
                kind: 'dot-grid',
                opacity: 0.92,
                embeddedOpacity: 0.46,
                dotRadius: 1.05,
            },
            panelBackdropFilter: 'saturate(1.08)',
            panelSurfaceTreatment: 'enamel',
            nodeSurfaceTreatment: 'crisp-sheet',
            gridStep: 32,
            gridMajorEvery: 4,
            nodeShadowBlur: 9,
            nodeSelectedShadowBlur: 15,
            nodeShadowOffsetY: 4,
        },
        motion,
        components,
    },
    nightLedger: {
        id: 'nightLedger',
        name: 'Night Ledger',
        mode: 'dark',
        description: 'Dark production workspace with strong surface separation.',
        colors: {
            canvas: {
                background: '#07090b',
                grid: 'rgba(132, 152, 166, 0.11)',
                gridMajor: 'rgba(166, 184, 198, 0.25)',
                paneFill: 'rgba(11, 14, 17, 0.94)',
                paneBorder: 'rgba(156, 174, 189, 0.46)',
                paneBorderInner: 'rgba(242, 247, 250, 0.07)',
                paneResizer: 'rgba(207, 219, 229, 0.28)',
                paneResizerMuted: 'rgba(207, 219, 229, 0.16)',
                paneResizerStrong: 'rgba(245, 249, 252, 0.82)',
                parentShape: 'rgba(172, 188, 202, 0.28)',
                parentShapeBorder: 'rgba(241, 247, 251, 0.48)',
                portalShape: 'rgba(122, 176, 211, 0.2)',
                portalShapeBorder: 'rgba(122, 176, 211, 0.74)',
            },
            panel: {
                surface: 'rgba(16, 19, 22, 0.98)',
                surfaceMuted: 'rgba(242, 247, 250, 0.075)',
                surfaceRaised: '#101316',
                border: '#4f5d66',
                borderStrong: '#aebbc5',
            },
            node: {
                surface: '#181d21',
                border: '#596772',
                selected: '#7ab0d3',
                resizeFill: '#d0b64f',
                shadow: 'rgba(0, 0, 0, 0.62)',
                task: '#7ab0d3',
                data: '#74c49a',
                system: '#d0a85a',
            },
            text: {
                high: '#f4f8fb',
                body: '#d8e1e8',
                muted: '#a9b7c2',
                inverse: '#07090b',
                placeholder: '#bfccd5',
            },
            action: {
                primary: '#7ab0d3',
                primaryHover: '#a6cce4',
                primarySoft: 'rgba(122, 176, 211, 0.2)',
                focus: '#d9effc',
            },
            state: {
                success: '#74c49a',
                successSoft: 'rgba(116, 196, 154, 0.18)',
                warning: '#d0b64f',
                warningSoft: 'rgba(208, 182, 79, 0.2)',
                error: '#ef8c8c',
                errorSoft: 'rgba(239, 140, 140, 0.18)',
            },
            overlay: {
                scrim: 'rgba(0, 0, 0, 0.68)',
                hover: 'rgba(244, 248, 251, 0.1)',
                active: 'rgba(244, 248, 251, 0.15)',
            },
        },
        typography,
        spacing,
        radius,
        borders,
        shadows: {
            chrome: '0 8px 24px rgba(0, 0, 0, 0.52)',
            node: '0 6px 12px rgba(0, 0, 0, 0.58)',
            nodeSelected: '0 7px 16px rgba(0, 0, 0, 0.62)',
            modal: '0 18px 48px rgba(0, 0, 0, 0.62)',
            menu: '0 12px 34px rgba(0, 0, 0, 0.54)',
        },
        texture: {
            ...flatTexture,
            canvasPattern: {
                ...flatTexture.canvasPattern,
                kind: 'line-grid',
                opacity: 0.82,
                embeddedOpacity: 0.44,
            },
            panelSurfaceTreatment: 'ink-metal',
            nodeSurfaceTreatment: 'solid-ledger',
            gridStep: 32,
            gridMajorEvery: 4,
            gridLineWidth: 1.05,
            nodeRestBorderWidth: 1.4,
            nodeHoverBorderWidth: 2,
            nodeSelectedBorderWidth: 2.6,
            nodePrimaryBorderWidth: 3.2,
            nodeShadowBlur: 12,
            nodeSelectedShadowBlur: 18,
            nodeShadowOffsetY: 6,
        },
        motion,
        components,
    },
    surveyMap: {
        id: 'surveyMap',
        name: 'Survey Map',
        mode: 'light',
        description: 'Spatial canvas theme for nested orientation.',
        colors: {
            canvas: {
                background: '#e6eef0',
                grid: 'rgba(45, 96, 102, 0.18)',
                gridMajor: 'rgba(25, 74, 82, 0.34)',
                paneFill: 'rgba(247, 252, 252, 0.96)',
                paneBorder: 'rgba(43, 83, 89, 0.4)',
                paneBorderInner: 'rgba(255, 255, 255, 0.9)',
                paneResizer: 'rgba(43, 83, 89, 0.26)',
                paneResizerMuted: 'rgba(43, 83, 89, 0.15)',
                paneResizerStrong: 'rgba(16, 56, 63, 0.64)',
                parentShape: 'rgba(44, 101, 108, 0.22)',
                parentShapeBorder: 'rgba(16, 74, 83, 0.44)',
                portalShape: 'rgba(0, 111, 130, 0.16)',
                portalShapeBorder: 'rgba(0, 111, 130, 0.62)',
            },
            panel: {
                surface: 'rgba(247, 252, 252, 0.98)',
                surfaceMuted: 'rgba(16, 74, 83, 0.06)',
                surfaceRaised: '#f7fcfc',
                border: '#acc3c7',
                borderStrong: 'rgba(16, 74, 83, 0.38)',
            },
            node: {
                surface: '#fbffff',
                border: '#a8c3c8',
                selected: '#006f82',
                resizeFill: '#8b6b1e',
                shadow: 'rgba(16, 74, 83, 0.12)',
                task: '#006f82',
                data: '#2f7f66',
                system: '#8b6b1e',
            },
            text: {
                high: '#16343a',
                body: '#334e54',
                muted: '#60787e',
                inverse: '#ffffff',
                placeholder: '#526e75',
            },
            action: {
                primary: '#006f82',
                primaryHover: '#005968',
                primarySoft: 'rgba(0, 111, 130, 0.13)',
                focus: '#006f82',
            },
            state: {
                success: '#2f7f66',
                successSoft: 'rgba(47, 127, 102, 0.13)',
                warning: '#8b6b1e',
                warningSoft: 'rgba(139, 107, 30, 0.14)',
                error: '#a72e3a',
                errorSoft: 'rgba(167, 46, 58, 0.12)',
            },
            overlay: {
                scrim: 'rgba(22, 52, 58, 0.32)',
                hover: 'rgba(22, 52, 58, 0.075)',
                active: 'rgba(22, 52, 58, 0.12)',
            },
        },
        typography,
        spacing,
        radius,
        borders,
        shadows: {
            chrome: '0 10px 24px rgba(16, 74, 83, 0.13)',
            node: '0 4px 10px rgba(16, 74, 83, 0.1)',
            nodeSelected: '0 7px 16px rgba(16, 74, 83, 0.16)',
            modal: '0 18px 44px rgba(16, 74, 83, 0.22)',
            menu: '0 12px 26px rgba(16, 74, 83, 0.17)',
        },
        texture: {
            ...flatTexture,
            canvasPattern: {
                ...flatTexture.canvasPattern,
                kind: 'dashed-grid',
                opacity: 0.9,
                embeddedOpacity: 0.48,
            },
            panelSurfaceTreatment: 'survey-sheet',
            nodeSurfaceTreatment: 'mapped-card',
            gridStep: 28,
            gridMajorEvery: 5,
            gridLineWidth: 0.9,
            gridDash: [5, 5],
            nodeRadius: 6,
            nodeShadowBlur: 7,
            nodeSelectedShadowBlur: 12,
            nodeShadowOffsetY: 3,
        },
        motion,
        components,
    },
    operationsRoom: {
        id: 'operationsRoom',
        name: 'Review Room',
        mode: 'light',
        description: 'High-contrast review theme for shared screens.',
        colors: {
            canvas: {
                background: '#eef2f5',
                grid: 'rgba(12, 20, 27, 0.2)',
                gridMajor: 'rgba(12, 20, 27, 0.42)',
                paneFill: 'rgba(255, 255, 255, 0.98)',
                paneBorder: 'rgba(12, 20, 27, 0.5)',
                paneBorderInner: 'rgba(255, 255, 255, 0.94)',
                paneResizer: 'rgba(12, 20, 27, 0.32)',
                paneResizerMuted: 'rgba(12, 20, 27, 0.2)',
                paneResizerStrong: 'rgba(12, 20, 27, 0.82)',
                parentShape: 'rgba(12, 20, 27, 0.22)',
                parentShapeBorder: 'rgba(12, 20, 27, 0.64)',
                portalShape: 'rgba(33, 86, 154, 0.16)',
                portalShapeBorder: 'rgba(33, 86, 154, 0.76)',
            },
            panel: {
                surface: 'rgba(255, 255, 255, 0.99)',
                surfaceMuted: 'rgba(12, 20, 27, 0.075)',
                surfaceRaised: '#ffffff',
                border: '#52606d',
                borderStrong: '#0c141b',
            },
            node: {
                surface: '#ffffff',
                border: '#4f5d69',
                selected: '#214f9a',
                resizeFill: '#9b5a13',
                shadow: 'rgba(12, 20, 27, 0.17)',
                task: '#214f9a',
                data: '#1d6f50',
                system: '#8a5a14',
            },
            text: {
                high: '#0c141b',
                body: '#26333d',
                muted: '#4f5d69',
                inverse: '#ffffff',
                placeholder: '#465562',
            },
            action: {
                primary: '#214f9a',
                primaryHover: '#173d7e',
                primarySoft: 'rgba(33, 79, 154, 0.14)',
                focus: '#0c141b',
            },
            state: {
                success: '#1d6f50',
                successSoft: 'rgba(29, 111, 80, 0.14)',
                warning: '#8a5a14',
                warningSoft: 'rgba(138, 90, 20, 0.15)',
                error: '#a92535',
                errorSoft: 'rgba(169, 37, 53, 0.13)',
            },
            overlay: {
                scrim: 'rgba(12, 20, 27, 0.42)',
                hover: 'rgba(12, 20, 27, 0.09)',
                active: 'rgba(12, 20, 27, 0.14)',
            },
        },
        typography,
        spacing,
        radius,
        borders,
        shadows: {
            chrome: '0 8px 14px rgba(12, 20, 27, 0.16)',
            node: '0 4px 8px rgba(12, 20, 27, 0.16)',
            nodeSelected: '0 5px 10px rgba(12, 20, 27, 0.18)',
            modal: '0 18px 44px rgba(12, 20, 27, 0.28)',
            menu: '0 10px 22px rgba(12, 20, 27, 0.2)',
        },
        texture: {
            ...flatTexture,
            canvasPattern: {
                ...flatTexture.canvasPattern,
                kind: 'line-grid',
                opacity: 0.92,
                embeddedOpacity: 0.54,
            },
            panelSurfaceTreatment: 'review-solid',
            paneGutter: '14px',
            nodeSurfaceTreatment: 'outlined',
            gridStep: 36,
            gridMajorEvery: 3,
            gridLineWidth: 1.2,
            nodeRadius: 5,
            nodeRestBorderWidth: 1.6,
            nodeHoverBorderWidth: 2.2,
            nodeSelectedBorderWidth: 3,
            nodePrimaryBorderWidth: 3.6,
            nodeShadowBlur: 5,
            nodeSelectedShadowBlur: 8,
            nodeShadowOffsetY: 3,
        },
        motion,
        components,
    },
    graphiteDesk: {
        id: 'graphiteDesk',
        name: 'Plum Desk',
        mode: 'dark',
        description: 'Warm professional workspace with restrained rose actions.',
        colors: {
            canvas: {
                background: '#241f28',
                grid: 'rgba(217, 184, 200, 0.12)',
                gridMajor: 'rgba(232, 202, 216, 0.25)',
                paneFill: 'rgba(43, 36, 46, 0.93)',
                paneBorder: 'rgba(222, 190, 207, 0.42)',
                paneBorderInner: 'rgba(255, 239, 247, 0.06)',
                paneResizer: 'rgba(232, 202, 216, 0.25)',
                paneResizerMuted: 'rgba(232, 202, 216, 0.15)',
                paneResizerStrong: 'rgba(255, 235, 247, 0.76)',
                parentShape: 'rgba(222, 190, 207, 0.24)',
                parentShapeBorder: 'rgba(255, 235, 247, 0.38)',
                portalShape: 'rgba(220, 133, 136, 0.18)',
                portalShapeBorder: 'rgba(220, 133, 136, 0.68)',
            },
            panel: {
                surface: 'rgba(49, 41, 53, 0.98)',
                surfaceMuted: 'rgba(255, 235, 247, 0.06)',
                surfaceRaised: '#312935',
                border: '#665263',
                borderStrong: 'rgba(255, 235, 247, 0.4)',
            },
            node: {
                surface: '#3a303b',
                border: '#715a6d',
                selected: '#dc8588',
                resizeFill: '#d6ad62',
                shadow: 'rgba(0, 0, 0, 0.42)',
                task: '#dc8588',
                data: '#78ae92',
                system: '#d6ad62',
            },
            text: {
                high: '#fff0f5',
                body: '#ead7e2',
                muted: '#c0a8b8',
                inverse: '#241f28',
                placeholder: '#d8c0ce',
            },
            action: {
                primary: '#dc8588',
                primaryHover: '#f1a3a6',
                primarySoft: 'rgba(220, 133, 136, 0.18)',
                focus: '#f1a3a6',
            },
            state: {
                success: '#78ae92',
                successSoft: 'rgba(120, 174, 146, 0.18)',
                warning: '#d6ad62',
                warningSoft: 'rgba(214, 173, 98, 0.18)',
                error: '#ee8c8f',
                errorSoft: 'rgba(176, 62, 72, 0.28)',
            },
            overlay: {
                scrim: 'rgba(0, 0, 0, 0.5)',
                hover: 'rgba(255, 240, 245, 0.08)',
                active: 'rgba(255, 240, 245, 0.13)',
            },
        },
        typography,
        spacing,
        radius,
        borders,
        shadows: {
            chrome: '0 12px 28px rgba(0, 0, 0, 0.34)',
            node: '0 6px 12px rgba(0, 0, 0, 0.38)',
            nodeSelected: '0 8px 18px rgba(0, 0, 0, 0.42)',
            modal: '0 18px 48px rgba(0, 0, 0, 0.48)',
            menu: '0 14px 32px rgba(0, 0, 0, 0.42)',
        },
        texture: {
            ...flatTexture,
            canvasPattern: {
                ...flatTexture.canvasPattern,
                kind: 'hatch-grid',
                opacity: 0.58,
                embeddedOpacity: 0.34,
                hatchAngle: -24,
                hatchLength: 9,
            },
            panelBackdropFilter: 'saturate(1.05)',
            panelSurfaceTreatment: 'warm-solid',
            nodeSurfaceTreatment: 'pressed-board',
            gridStep: 34,
            gridMajorEvery: 4,
            nodeRadius: 7,
            nodeShadowBlur: 11,
            nodeSelectedShadowBlur: 18,
            nodeShadowOffsetY: 6,
        },
        motion,
        components,
    },
};

export const canasterThemeOptions = Object.values(CANASTER_THEMES);

export function isCanasterThemeId(value: string): value is CanasterThemeId {
    return Object.prototype.hasOwnProperty.call(CANASTER_THEMES, value);
}

export function normalizeCanasterThemeId(value: string | null | undefined): CanasterThemeId {
    return value && isCanasterThemeId(value) ? value : DEFAULT_CANASTER_THEME_ID;
}

export function canasterThemeById(value: string | null | undefined): CanasterTheme {
    return CANASTER_THEMES[normalizeCanasterThemeId(value)];
}
